### ISSUE TITLE
Merge XCode packages

### ISSUE THREAD

**Issue by michaelblyons** [peterthomashorn/strings-resource-file-language-for-sublime-text#1]
You can have >1 syntax definition per package. Might you consider bundling all three together if you imagine people who want one might have an interest in the other two?

**Comment by p4t5h3** [comment]
As stated in [the related pull request](https://github.com/wbond/package_control_channel/pull/8391), I think I should rename and exclude at least this syntax definition (xcode-strings-language-for-sublime-text) for [it is not related to only Xcode but to the Apple platform in general](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/LoadingResources/Strings/Strings.html). I saw it too late and then it already got merged. Besides that one might still be relevant for users which do not work with Xcode. In example system administrators [localizing directories on macOS](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemAdvancedPT/LocalizingtheNameofaDirectory/LocalizingtheNameofaDirectory.html#//apple_ref/doc/uid/TP40010765-CH4-SW1).

I also understand the argument of convenience to bundle them and wish meta packages for bundling related packages would exist ([which do not](https://packagecontrol.io/docs/dependencies)). As already stated in the related pull request I do not feel convinced the bundling is a good idea because it waters down the purpose of the package. I am still thinking about it, though.

Just in case I guess `Xcode-languages-for-sublime-text` would be the appropriate package name then.

**Comment by michaelblyons** [comment]
Thanks for the reply. I concede that this one could be good to exclude from a bundle. The other two, though, could be merged. (I think you can remove one from PC and put in the "old names" for the other one you consolidate to.)

**Comment by p4t5h3** [comment]
I renamed the package and am waiting for [the pull request to be accepted](https://github.com/wbond/package_control_channel/pull/8401) for now. Then I will get back to this.

**Comment by p4t5h3** [comment]
The previously mentioned pull request was merged. I will take a look on how to merge the packages.

**Comment by p4t5h3** [comment]
The merged package is [here](https://github.com/peterthomashorn/xcode-languages-for-sublime-text). Once it is published I will archive the predecessors. The pull request for the publication is [here](https://github.com/wbond/package_control_channel/pull/8451). Because the string resource files are the only one not fitting  in there I will close this issue in this context.
